[project]
name = "mission_odyssey"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.7",
    "numpy>=2.3.3",
    "rocketpy>=1.10.0",
    "scipy>=1.16.2",
]
